[build]
  publish = "dist"
  command = "npm run build"

# This ensures static assets are properly prioritized before SPA routes
[[redirects]]
  from = "/pamomo-preview.png"
  to = "/pamomo-preview.png"
  status = 200
  force = true

# This handles SPA routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# This ensures static assets are cached properly
[[headers]]
  for = "/pamomo-preview.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"